--SECUENCIAS---
--DROP SECUENCIAS-------
DROP SEQUENCE seq_id_usuario;
DROP SEQUENCE seq_id_deuda;
DROP SEQUENCE seq_id_ingreso;
DROP SEQUENCE seq_id_inversion;
DROP SEQUENCE seq_id_tarjeta;
DROP SEQUENCE seq_id_amigo;
DROP SEQUENCE seq_id_categoria;
DROP SEQUENCE seq_id_historial;
DROP SEQUENCE seq_id_configuracion;
DROP SEQUENCE seq_id_trabajo;
DROP SEQUENCE seq_id_ahorro;
DROP SEQUENCE seq_id_gasto;
--------------------------
---CREACION SECUENCIAS---
CREATE SEQUENCE seq_id_usuario
START WITH 1
MAXVALUE 99999999999999             
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_deuda
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_ingreso
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_inversion
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_tarjeta
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_amigo
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_categoria
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_historial
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_configuracion
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
------------------
CREATE SEQUENCE seq_id_config_usuario
START WITH 1
MAXVALUE 999999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_trabajo
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_ahorro
START WITH 1
MAXVALUE 99999999999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_prestamo
START WITH 1
MAXVALUE 99999999
INCREMENT BY 1;
-----------------
CREATE SEQUENCE seq_id_gastos
START WITH 1
MAXVALUE 99999999
INCREMENT BY 1;
---TABLAS-------
--DROP TABLAS-------------
DROP TABLE USUARIO;
DROP TABLE DEUDA;
DROP TABLE INGRESO;
DROP TABLE INVERSION;
DROP TABLE TARJETA;
DROP TABLE AMIGO;
DROP TABLE CATEGORIA;
DROP TABLE HISTORIAL;
DROP TABLE CONFIGURACION;
DROP TABLE CONFIG_USER;
DROP TABLE TRABAJO;
DROP TABLE AHORRO;
DROP TABLE PRESTAMO;
DROP TABLE GASTO;
----------------------------
--CREACION DE TABLAS--

--CREAR TABLA DEUDAS--
CREATE TABLE DEUDA(
id_deuda NUMBER(10) NOT NULL,
id_usuario NUMBER(10) NOT NULL,
id_categoria NUMBER(10) NOT NULL,
id_tarjeta NUMBER(10) NOT NULL,
id_amigo NUMBER(10),
amigo VARCHAR(10),
categoria VARCHAR2(20) NOT NULL,
descripcion VARCHAR2(30) NOT NULL,
nombre VARCHAR2(20) NOT NULL,
total NUMBER(20) NOT NULL,
tarjeta VARCHAR2(15),
cuotas NUMBER(3),
porcentaje NUMBER(4),
fecha_ingreso DATE,
fecha_vencimiento DATE);
-----------------------------------
--CREAR TABLA INGRESOS--
CREATE TABLE INGRESO(
id_ingreso NUMBER(10) NOT NULL,
id_usuario NUMBER(10) NOT NULL,
id_categoria NUMBER(10) NOT NULL,
id_tarjeta NUMBER(10) NOT NULL,
categoria VARCHAR2(20) NOT NULL,
descripcion VARCHAR2(30) NOT NULL,
nombre VARCHAR2(20) NOT NULL,
total NUMBER(20) NOT NULL,
tarjeta VARCHAR2(15),
fecha_ingreso DATE NOT NULL,
fecha_vencimiento DATE NOT NULL);
---------------------------------------------
--CREAR TABLA TARJETAS--
CREATE TABLE TARJETA(
id_tarjeta NUMBER(10) NOT NULL,
nombre VARCHAR(20) NOT NULL,
id_usuario NUMBER(10) NOT NULL,
tipo_tarjeta Varchar(20),
cantidad NUMBER(20));
-----------------------------------------------

--CREAR TABLA INVERSIONES--
CREATE TABLE INVERSION(
id_inversion NUMBER(10) NOT NULL,
id_usuario NUMBER(10) NOT NULL,
id_categoria NUMBER(10) NOT NULL,
id_tarjeta NUMBER(10) NOT NULL,
descripcion VARCHAR2(30),
categoria VARCHAR2(20) NOT NULL,
nombre VARCHAR2(20) NOT NULL,
total NUMBER(20) NOT NULL,
porcentaje NUMBER(4),
tarjeta VARCHAR2(15),
fecha_ingreso DATE NOT NULL,
fecha_vencimiento DATE);
---------------------------
--CREAR TABLA  HISTORIAL--
CREATE TABLE HISTORIAL(
id_historial NUMBER(10) NOT NULL,
id_usuario NUMBER(10) NOT NULL,
id_amigo NUMBER(10),
id_tarjeta NUMBER(10) NOT NULL,
desc_suceso VARCHAR2(40) NOT NULL,
fecha_suceso DATE NOT NULL,
total NUMBER (20));
--CREAR TABLA AMIGOS--
CREATE TABLE AMIGO(
id_amigo NUMBER(10) NOT NULL,
user_id NUMBER(10) NOT NULL,
friend_id NUMBER(10) NOT NULL,
estado VARCHAR(15) NOT NULL,
fecha DATE NOT NULL);
--CREAR TABLA CATEGORIAS--
CREATE TABLE CATEGORIA(
id_categoria NUMBER(10) NOT NULL,
nombre VARCHAR(15) NOT NULL,
id_usuario NUMBER(10) NOT NULL,
img BLOB);

--CREAR TABLA CONFIG_USER--
CREATE TABLE CONFIG_USER(
id_config_user NUMBER(10) NOT NULL,
id_configuracion NUMBER(10),
id_usuario NUMBER(10) NOT NULL,
nombre VARCHAR2(20));
--CREAR TABLA CONFIGURACION REAL---
CREATE TABLE CONFIGURACION(
id_configuracion NUMBER(10) NOT NULL,
nombre VARCHAR2(20),
descripcion VARCHAR2(100));
--CREAR TABLA TRABAJOS--
CREATE TABLE TRABAJO(
id_trabajo NUMBER(10) NOT NULL,
nombre VARCHAR2(15) NOT NULL,
salario NUMBER(15) NOT NULL,
horas_trabajo NUMBER(4) NOT NULL,
dias NUMBER(2),
id_usuario NUMBER(10) NOT NULL);
--CREAR TABLA USUARIO--
CREATE TABLE USUARIO
(id_usuario NUMBER(10),
name_user VARCHAR2(20),
ap_user VARCHAR2(20),
username VARCHAR2(10),
mail VARCHAR2(20),
pasword VARCHAR2(100),
estado VARCHAR2(20));
--------------------------
--CREAR TABLA AHORROS---
CREATE TABLE AHORRO(
id_ahorro NUMBER(10) NOT NULL,
id_usuario NUMBER(10) NOT NULL,
id_categoria NUMBER(10) NOT NULL,
id_tarjeta NUMBER(10) NOT NULL,
categoria VARCHAR2(20) NOT NULL,
descripcion VARCHAR(30) NOT NULL,
nombre VARCHAR2(20) NOT NULL,
total NUMBER(20) NOT NULL,
tarjeta VARCHAR2(15),
fecha_ingreso DATE NOT NULL,
fecha_vencimiento DATE NOT NULL);
--CREACION DE TABLA ´PRESTAMOS----
CREATE TABLE PRESTAMO(
id_prestamo NUMBER(10) NOT NULL,
id_prestamista NUMBER(10) NOT NULL,
id_tarjeta NUMBER(10),
id_categoria NUMBER(10),
id_amigo NUMBER(10),
id_usuario NUMBER(10),
user_prestamo VARCHAR2(30),
correo_prestamo VARCHAR(40),
user_friend VARCHAR2(30),
categoria VARCHAR2(30),
cantidad NUMBER(10) ,
descripcion VARCHAR2(30),
fecha_ingreso DATE,
fecha_vencimiento DATE);
---CREACION TABLA GASTOS----
CREATE TABLE GASTO(
id_gasto NUMBER(10) NOT NULL,
id_usuario NUMBER(10) NOT NULL,
id_categoria NUMBER(10) NOT NULL,
id_tarjeta NUMBER(10) NOT NULL,
categoria VARCHAR2(20) NOT NULL,
descripcion VARCHAR(30) NOT NULL,
nombre VARCHAR2(20) NOT NULL,
total NUMBER(20) NOT NULL,
tarjeta VARCHAR2(15),
fecha_ingreso DATE NOT NULL,
fecha_vencimiento DATE NOT NULL);

---ALTER TABLES----

--ALTER TABLE DEUDA---
ALTER TABLE DEUDA ADD CONSTRAINT pk_deuda PRIMARY KEY(id_deuda);
ALTER TABLE DEUDA ADD CONSTRAINT fk_user_ahorro FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario);
ALTER TABLE DEUDA ADD CONSTRAINT fk_tarjeta FOREIGN KEY(id_tarjeta) REFERENCES TARJETA(id_tarjeta);
ALTER TABLE DEUDA ADD CONSTRAINT fk_cat_deuda FOREIGN KEY(id_categoria) REFERENCES CATEGORIA(id_categoria);
ALTER TABLE DEUDA ADD CONSTRAINT fk_amigo FOREIGN KEY(id_amigo) REFERENCES AMIGO(id_amigo);
---ALTER TABLE GASTO---
ALTER TABLE GASTO ADD CONSTRAINT pk_gasto PRIMARY KEY(id_gasto);
ALTER TABLE GASTO ADD CONSTRAINT fk_user_gasto FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario);
ALTER TABLE GASTO ADD CONSTRAINT fk_tarjeta_gasto FOREIGN KEY(id_tarjeta) REFERENCES TARJETA(id_tarjeta);
ALTER TABLE GASTO ADD CONSTRAINT fk_cat_gasto FOREIGN KEY(id_categoria) REFERENCES CATEGORIA(id_categoria);
--ALTER TABLE INGRESO---
ALTER TABLE INGRESO ADD CONSTRAINT pk_ingreso PRIMARY KEY(id_ingreso);
ALTER TABLE INGRESO ADD CONSTRAINT fk_usuario FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario);
ALTER TABLE INGRESO ADD CONSTRAINT fk_tar_ingreso FOREIGN KEY(id_tarjeta) REFERENCES TARJETA(id_tarjeta);
ALTER TABLE INGRESO ADD CONSTRAINT fk_categoria FOREIGN KEY(id_categoria) REFERENCES CATEGORIA(id_categoria);
--ALTER TABLE TARJETA---
ALTER TABLE TARJETA ADD CONSTRAINT pk_tarjeta PRIMARY KEY(id_tarjeta);
--ALTER TABLE INVERSION---
ALTER TABLE INVERSION ADD CONSTRAINT pk_inversion PRIMARY KEY(id_inversion);
ALTER TABLE INVERSION ADD CONSTRAINT fk_user_inv FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario);
ALTER TABLE INVERSION ADD CONSTRAINT fk_tarj_inv FOREIGN KEY(id_tarjeta) REFERENCES TARJETA(id_tarjeta);
ALTER TABLE INVERSION ADD CONSTRAINT fk_cat_inv FOREIGN KEY(id_categoria) REFERENCES CATEGORIA(id_categoria);
--ALTER TABLE HISTORIAL---
ALTER TABLE HISTORIAL ADD CONSTRAINT pk_historial PRIMARY KEY (id_historial);
ALTER TABLE HISTORIAL ADD CONSTRAINT fk_tarj FOREIGN KEY(id_tarjeta) REFERENCES TARJETA(id_tarjeta);
ALTER TABLE HISTORIAL ADD CONSTRAINT fk_user_histori FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario);

--ALTER TABLE AMIGO---
ALTER TABLE AMIGO ADD CONSTRAINT pk_amigo PRIMARY KEY (id_amigo);
ALTER TABLE AMIGO ADD CONSTRAINT fk_user_friend FOREIGN KEY(user_id) REFERENCES USUARIO(id_usuario);
ALTER TABLE AMIGO ADD CONSTRAINT fk_frined_user FOREIGN KEY(friend_id) REFERENCES USUARIO(id_usuario);
--ALTER TABLE CATEGORIA---
ALTER TABLE CATEGORIA ADD CONSTRAINT pk_categoria PRIMARY KEY (id_categoria);
ALTER TABLE CATEGORIA ADD CONSTRAINT fk_user_cat FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario);
--ALTER TABLE CONFIGURACION---
ALTER TABLE CONFIGURACION ADD CONSTRAINT pk_configuracion PRIMARY KEY (id_configuracion);
--ALTER TABLE CONFIG_USER-------
ALTER TABLE CONFIG_USER ADD CONSTRAINT pk_config_user PRIMARY KEY (id_config_user);
ALTER TABLE CONFIG_USER ADD CONSTRAINT fk_user_config FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario);
ALTER TABLE CONFIG_USER ADD CONSTRAINT fk_config FOREIGN KEY (id_configuracion) REFERENCES CONFIGURACION(id_configuracion);
--ALTER TABLE TRABAJO---
ALTER TABLE TRABAJO ADD CONSTRAINT pk_trabajo PRIMARY KEY (id_trabajo);
ALTER TABLE TRABAJO ADD CONSTRAINT fk_user_trabajo FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario);
--ALTER TABLE USUARIO---
ALTER TABLE USUARIO ADD CONSTRAINT pk_usuario PRIMARY KEY (id_usuario);
--ALTER TABLE AHORRO---
ALTER TABLE AHORRO ADD CONSTRAINT pk_ahorro PRIMARY KEY(id_ahorro);
ALTER TABLE AHORRO ADD CONSTRAINT fk_user_ahorroo FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario);
ALTER TABLE AHORRO ADD CONSTRAINT fk_tar_ahorro FOREIGN KEY(id_tarjeta) REFERENCES TARJETA(id_tarjeta);
ALTER TABLE AHORRO ADD CONSTRAINT fk_cat_ahorro FOREIGN KEY(id_categoria) REFERENCES CATEGORIA(id_categoria);
--ALTER TABLE PRESTAMOS---
ALTER TABLE PRESTAMO ADD CONSTRAINT pk_prestamo PRIMARY KEY(id_prestamo);
ALTER TABLE PRESTAMO ADD CONSTRAINT fk_user_prestamo FOREIGN KEY(id_usuario) REFERENCES USUARIO(id_usuario);
ALTER TABLE PRESTAMO ADD CONSTRAINT fk_amigo_prestamo FOREIGN KEY(id_amigo) REFERENCES USUARIO(id_usuario);
ALTER TABLE PRESTAMO ADD CONSTRAINT fk_tarj_prestamo FOREIGN KEY(id_tarjeta) REFERENCES TARJETA(id_tarjeta);
id_prestamo NUMBER(10) NOT NULL,
id_tarjeta NUMBER(10),
id_categoria NUMBER(10),
id_amigo NUMBER(10),
id_usuario NUMBER(10),
